title: n3mo's homepage
description: homepage for n3mo's bookmarks and services
background:
  image: /images/wallpaper.jpg
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50
theme: dark
headerStyle: clean
target: _self
layout: